export const irsCategories = [
  { value: "Select", title: "Select your IRS Category", disabled: true },
  { value: "Unknown", title: "Unknown" },
  {
    value: "501(c)(1) – Corporations Organized Under Act of Congress",
    title: "501(c)(1) – Corporations Organized Under Act of Congress",
  },
  {
    value: "501(c)(2) – Title Holding Corporations for Exempt Organizations",
    title: "501(c)(2) – Title Holding Corporations for Exempt Organizations",
  },
  {
    value: "501(c)(3) – Religious, Educational, Charitable Organizations",
    title: "501(c)(3) – Religious, Educational, Charitable Organizations",
  },
  {
    value: "501(c)(4) – Civic Leagues, Social Welfare Organizations",
    title: "501(c)(4) – Civic Leagues, Social Welfare Organizations",
  },
  {
    value: "501(c)(5) – Labor, Agricultural, Horticultural Organizations",
    title: "501(c)(5) – Labor, Agricultural, Horticultural Organizations",
  },
  {
    value: "501(c)(6) – Business Leagues, Chambers of Commerce",
    title: "501(c)(6) – Business Leagues, Chambers of Commerce",
  },
  {
    value: "501(c)(7) – Social and Recreational Clubs",
    title: "501(c)(7) – Social and Recreational Clubs",
  },
  {
    value: "501(c)(8) – Fraternal Beneficiary Societies and Associations",
    title: "501(c)(8) – Fraternal Beneficiary Societies and Associations",
  },
  {
    value: "501(c)(9) – Voluntary Employees' Beneficiary Associations",
    title: "501(c)(9) – Voluntary Employees' Beneficiary Associations",
  },
  {
    value: "501(c)(10) – Domestic Fraternal Societies and Associations",
    title: "501(c)(10) – Domestic Fraternal Societies and Associations",
  },
  {
    value: "501(c)(11) – Teachers’ Retirement Fund Associations",
    title: "501(c)(11) – Teachers’ Retirement Fund Associations",
  },
  {
    value:
      "501(c)(12) – Benevolent Life Insurance Associations, Mutual Ditch or Irrigation Companies, Mutual or Cooperative Telephone Companies",
    title:
      "501(c)(12) – Benevolent Life Insurance Associations, Mutual Ditch or Irrigation Companies, Mutual or Cooperative Telephone Companies",
  },
  {
    value: "501(c)(13) – Cemetery Companies",
    title: "501(c)(13) – Cemetery Companies",
  },
  {
    value: "501(c)(14) – State-Chartered Credit Unions, Mutual Reserve Funds",
    title: "501(c)(14) – State-Chartered Credit Unions, Mutual Reserve Funds",
  },
  {
    value: "501(c)(15) – Mutual Insurance Companies or Associations",
    title: "501(c)(15) – Mutual Insurance Companies or Associations",
  },
  {
    value: "501(c)(16) – Cooperative Organizations to Finance Crop Operations",
    title: "501(c)(16) – Cooperative Organizations to Finance Crop Operations",
  },
  {
    value: "501(c)(17) – Supplemental Unemployment Benefit Trusts",
    title: "501(c)(17) – Supplemental Unemployment Benefit Trusts",
  },
  {
    value: "501(c)(18) – Employee Funded Pension Trusts",
    title: "501(c)(18) – Employee Funded Pension Trusts",
  },
  {
    value:
      "501(c)(19) – Post or Organization of Past or Present Members of the Armed Forces",
    title:
      "501(c)(19) – Post or Organization of Past or Present Members of the Armed Forces",
  },
  {
    value: "501(c)(20) – Group Legal Services Plan Organizations",
    title: "501(c)(20) – Group Legal Services Plan Organizations",
  },
  {
    value: "501(c)(21) – Black Lung Benefit Trusts",
    title: "501(c)(21) – Black Lung Benefit Trusts",
  },
  {
    value: "501(c)(22) – Withdrawal Liability Payment Funds",
    title: "501(c)(22) – Withdrawal Liability Payment Funds",
  },
  {
    value: "501(c)(23) – Veterans Organization (created before 1880)",
    title: "501(c)(23) – Veterans Organization (created before 1880)",
  },
  {
    value: "501(c)(24) – Trusts described in section 4049 of ERISA",
    title: "501(c)(24) – Trusts described in section 4049 of ERISA",
  },
  {
    value:
      "501(c)(25) – Title Holding Corporations or Trusts with Multiple Parents",
    title:
      "501(c)(25) – Title Holding Corporations or Trusts with Multiple Parents",
  },
  {
    value:
      "501(c)(26) – State-Sponsored Organization Providing Health Coverage for High-Risk Individuals",
    title:
      "501(c)(26) – State-Sponsored Organization Providing Health Coverage for High-Risk Individuals",
  },
  {
    value:
      "501(c)(27) – State-Sponsored Workers' Compensation Reinsurance Organization",
    title:
      "501(c)(27) – State-Sponsored Workers' Compensation Reinsurance Organization",
  },
  {
    value: "501(c)(28) – National Railroad Retirement Investment Trust",
    title: "501(c)(28) – National Railroad Retirement Investment Trust",
  },
  {
    value: "501(d) – Religious and Apostolic Associations",
    title: "501(d) – Religious and Apostolic Associations",
  },
  {
    value: "501(e) – Cooperative Hospital Service Organizations",
    title: "501(e) – Cooperative Hospital Service Organizations",
  },
  {
    value:
      "501(f) – Cooperative Service Organizations of Operating Educational Organizations",
    title:
      "501(f) – Cooperative Service Organizations of Operating Educational Organizations",
  },
  {
    value: "501(k) – Child Care Organizations",
    title: "501(k) – Child Care Organizations",
  },
  {
    value: "501(n) – Charitable Risk Pools",
    title: "501(n) – Charitable Risk Pools",
  },
  {
    value: "501(q) – Credit Counseling Organizations",
    title: "501(q) – Credit Counseling Organizations",
  },
];
export const industries = [
  { value: "Select", title: "Select your Industry", disabled: true },
  { value: "Agriculture", title: "Agriculture" },
  { value: "Automotive", title: "Automotive" },
  { value: "Banking", title: "Banking" },
  { value: "Construction", title: "Construction" },
  { value: "Consumer Goods", title: "Consumer Goods" },
  { value: "Education", title: "Education" },
  { value: "Energy", title: "Energy" },
  { value: "Entertainment", title: "Entertainment" },
  { value: "Financial Services", title: "Financial Services" },
  { value: "Food & Beverages", title: "Food & Beverages" },
  { value: "Government", title: "Government" },
  { value: "Healthcare", title: "Healthcare" },
  { value: "Hospitality", title: "Hospitality" },
  { value: "Insurance", title: "Insurance" },
  { value: "Manufacturing", title: "Manufacturing" },
  { value: "Media", title: "Media" },
  { value: "Non-Profit", title: "Non-Profit" },
  { value: "Pharmaceuticals", title: "Pharmaceuticals" },
  { value: "Real Estate", title: "Real Estate" },
  { value: "Retail", title: "Retail" },
  { value: "Technology", title: "Technology" },
  { value: "Telecommunications", title: "Telecommunications" },
  { value: "Transportation", title: "Transportation" },
  { value: "Utilities", title: "Utilities" },
  { value: "Other", title: "Other" },
];
export const organizationTypes = [
  { value: "Select", title: "Select your Organization Type", disabled: true },
  { value: "Business (For Profit)", title: "Business (For Profit)" },
  { value: "Non Profit", title: "Non Profit" },
  { value: "Government Entity", title: "Government Entity" },
  { value: "Educational Institution", title: "Educational Institution" },
  { value: "Healthcare Provider", title: "Healthcare Provider" },
  { value: "Residential", title: "Residential" },
  { value: "Other", title: "Other" },
];
export const companyOptions = [
  "Adobe",
  "Airbnb",
  "Alibaba",
  "Alphabet",
  "Amazon",
  "AMD",
  "Apple",
  "ASUS",
  "Atlassian",
  "Autodesk",
  "Baidu",
  "Bitdefender",
  "Block",
  "Bloomberg",
  "Broadcom",
  "Bytedance",
  "Canonical",
  "Cisco",
  "Cloudflare",
  "Coinbase",
  "Coursera",
  "Cruise",
  "CyberArk",
  "Databricks",
  "Datadog",
  "Dell",
  "DigitalOcean",
  "Discord",
  "DoorDash",
  "Dropbox",
  "eBay",
  "Epic Games",
  "Ericsson",
  "Etsy",
  "Evernote",
  "Expedia",
  "Figma",
  "FireEye",
  "Fortinet",
  "Foxconn",
  "GitHub",
  "GitLab",
  "GoDaddy",
  "Google",
  "GoPro",
  "Grab",
  "Hewlett Packard Enterprise",
  "Hitachi",
  "Honeywell",
  "Huawei",
  "Hulu",
  "IBM",
  "Infosys",
  "Intel",
  "Intuit",
  "iRobot",
  "JD.com",
  "JetBrains",
  "Kaspersky",
  "Keyence",
  "Kickstarter",
  "Lenovo",
  "LG",
  "Lyft",
  "Magic Leap",
  "Mastercard",
  "Match Group",
  "McAfee",
  "Meta",
  "Microsoft",
  "MicroStrategy",
  "MongoDB",
  "NCR",
  "NEC",
  "Netflix",
  "Nokia",
  "Nutanix",
  "Nvidia",
  "Okta",
  "Olympus",
  "Onfido",
  "OpenAI",
  "Oracle",
  "Palantir",
  "Panasonic",
  "PayPal",
  "Philips",
  "Pinterest",
  "Pivotal",
  "PlayStation",
  "Pure Storage",
  "Qualcomm",
  "Quora",
  "Rakuten",
  "Rapid7",
  "Red Hat",
  "Reddit",
  "Ripple",
  "Roblox",
  "Roku",
  "Salesforce",
  "Samsung",
  "SAP",
  "Seagate",
  "ServiceNow",
  "Shopify",
  "Siemens",
  "Slack",
  "Snapchat",
  "Snowflake",
  "SoftBank",
  "Sony",
  "SpaceX",
  "Spotify",
  "Square",
  "Stripe",
  "SUSE",
  "Synopsys",
  "T-Mobile",
  "Tableau",
  "Tencent",
  "Tesla",
  "TikTok",
  "Toshiba",
  "Toyota",
  "Trello",
  "TripAdvisor",
  "Twitch",
  "Twitter",
  "Uber",
  "Unity",
  "Upwork",
  "Verizon",
  "VMware",
  "Vimeo",
  "WeChat",
  "Western Digital",
  "WhatsApp",
  "Wix",
  "Xiaomi",
  "Xilinx",
  "Yahoo",
  "Yandex",
  "YouTube",
  "Zebra Technologies",
  "Zillow",
  "Zoom",
  "Zscaler",
];

 export  const waterTreatmentOptionsFlat = [
    "Closed-Loop: Inhibitors & Biocides",
    "Closed-Loop: Regular Testing (pH, Cond, Glycol)",
    "Closed-Loop: Scale, Corrosion, Microbio Prevention",
    "Open-Loop: Chemical Feed System",
    "Open-Loop: Conductivity & Auto Blowdown",
    "Open-Loop: Biocides, Algaecides, Anti-scalants",
    "Boiler: Water Softening, Scale/O2 Corrosion Prevention",
    "Boiler: Feedwater Dosing (O2 Scavengers, pH, Antiscalants)",
    "Boiler: Daily Chemistry Testing",
  ];